steps:
- name: node
  entrypoint: npm
  args: ['install']
- name: 'gcr.io/cloud-builders/npm'
  entrypoint: npm
  args:
      [
        'build',
        '-t',
        'gcr.io/psychic-timing-360520/harmonic-percussive-project:$SHORT_SHA',
        '.',
      ]
- name: 'gcr.io/cloud-builders/npm'
    args:
      [
        'push',
        'gcr.io/psychic-timing-360520/harmonic-percussive-project:$SHORT_SHA',
      ]

