steps:
- name: node
  entrypoint: npm
  args: ['install']
- name: node
  entrypoint: npm
  args:
      [
        'run',
        'gcr.io/psychic-timing-360520/harmonic-percussive-project:$SHORT_SHA',
      ]
- name: node
  entrypoint: npm
  args: 
      [
        'build',
        'gcr.io/psychic-timing-360520/harmonic-percussive-project:$SHORT_SHA',
      ]
 - name: 'gcr.io/cloud-builders/gcloud'
   args:
     [
       'beta',
       'run',
       'deploy',
       'cloud-run-continuous-deployment-example',
       '--image=gcr.io/psychic-timing-360520/harmonic-percussive-project:$SHORT_SHA',
       '--region=us-central1',
     ]
