steps:
- name: node
  entrypoint: npm
  args: ['install']
- name: node
    args:
      [
        'build',
        '-t',
        'gcr.io/psychic-timing-360520/harmonic-percussive-project:$SHORT_SHA',
        '.',
      ]
  - name: node
    args:
      [
        'push',
        'gcr.io/psychic-timing-360520/harmonic-percussive-project:$SHORT_SHA',
      ]
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
        'beta',
        'run',
        'deploy',
        'cloud-run-continuous-deployment-example',
        '--image=gcr.io/psychic-timing-360520/harmonic-percussive-project:$SHORT_SHA',
        '--region=us-central1',
      ]
