steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/harmonic-percussive-project/harmonic-percussive-project:SHORT_SHA', '.']
  - name: 'gcr.io/cloud-builders/docker'
  args: ['push', '-t', 'gcr.io/harmonic-percussive-project/harmonic-percussive-project:SHORT_SHA']
